config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "workouts#new"

  resources :workouts, only: [:index, :show, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :lift

  validates :weight, presence: true, numericality: true
  validates :reps, presence: true, numericality: true
end

app/models/lift.rb
class Lift < ApplicationRecord
  belongs_to :workout
  has_many :groups, dependent: :destroy
  accepts_nested_attributes_for :groups, allow_destroy: true

  validates :lift_name, presence: true
  validates  :groups, :length => { :minimum => 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :workouts
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :lifts, dependent: :destroy
  accepts_nested_attributes_for :lifts, allow_destroy: true

  validates :date, presence: true
  validates  :lifts, :length => { :minimum => 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @workouts = current_user.workouts.order(date: :desc)
  end

  def show
    @workout = Workout.find(params[:id])
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = current_user.workouts.build(workout_params)
    if @workout.save
      redirect_to workouts_path
    else
      flash.now[:error] = @workout.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy

    redirect_to workouts_path, status: :see_other
  end

  private
    def workout_params
      params.require(:workout).permit(:date, :workout_name, :total, 
        lifts_attributes: [:_destroy, :id, :lift_name,
          groups_attributes: [:_destroy, :id, :reps, :weight]])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weightmoved</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="p-3 flex justify-between bg-blue-200">
      <h1 class="font-playfair-display text-xl sm:text-3xl"><%= link_to "weightmoved", root_path %></h1>
      <div class="flex items-center justify-between">
        <% if user_signed_in? %>
          <%= link_to "Workouts", workouts_path, class: "mr-6" %>
          <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/workouts/_group_fields.html.erb
<div class="nested-fields">
  <%= form.hidden_field :_destroy %>
    <div class="flex justify-between">
      <div>
        <%= form.label :weight, 'Weight', class: "text-sm font-medium" %>
        <%= form.number_field :weight, required: true, type: "number", data: {
            calculator_target: "weight",
            action: "input->calculator#calculateTotalWeight"}, 
            class: "w-4/5 bg-slate-100 hover:bg-slate-200 border-0 border-b rounded-md" %>
      </div>
      <div>
        <%= form.label :reps, '# of Reps', class: "text-sm font-medium" %>
        <%= form.number_field :reps, required: true, type: "number", data: {
            calculator_target: "reps",
            action: "input->calculator#calculateTotalWeight"}, class: "w-4/5 bg-slate-100 hover:bg-slate-200 border-0 border-b rounded-md" %>
      </div>
      <div class="flex items-center">
        <%= link_to "#", data: { action: "nested-form#removeField" } do %>
          <%= image_tag("minus.svg", alt: "Remove", title: "Delete Set", class: "text-red-500 h-5 w-5 mt-4 mr-14") %>
        <% end %>
      </div>
    </div>
</div>

app/views/workouts/_lift_fields.html.erb
<div class="nested-fields border p-1">
  <%= form.hidden_field :_destroy %>
  <%= form.label :lift_name, 'Lift name', class: "text-sm font-medium" %><br>
  <%= form.text_field :lift_name, required: true, class: "rounded-md w-4/5" %><br>
  <div data-controller="nested-form">
    <%= form.fields_for :groups, Group.new, child_index: 0 do |group| %>
      <%= render 'group_fields', form: group %>
    <% end %>
    <template data-nested-form-target="groupTemplate">
      <%= form.fields_for :groups, Group.new, child_index: 'TEMPLATE_GROUP' do |group| %>
        <%= render 'group_fields', form: group %>
      <% end %>
    </template>
    <div data-nested-form-target="addGroup">
      <button class="text-green-700" data-action="click->nested-form#addGroup">Add Set</button>
    </div>
  </div>
  <%= link_to "Remove Lift", "#", data: { action: "nested-form#removeField"}, class: "text-red-500" %><br>
</div>

app/views/workouts/index.html.erb
<h1 class="text-center text-2xl p-2">Workout Log</h1>
<div class="flex justify-center">
  <table class="text-center">
    <thead>
      <tr>
        <th class="p-2 text-center">Date</th>
        <th class="p-2 text-center">Workout Name</th>
        <th class="p-2 text-center">Total</th>
        <th class="p-2 text-center">Lift Name</th>
        <th class="p-2 text-center">Reps</th>
        <th class="p-2 text-center">Weight</th>
      </tr>
    </thead>
    <tbody>
      <% @workouts.each do |workout| %>
        <% row_color = cycle('bg-gray-100', 'bg-white') %>
        <tr class="<%= row_color %>">
            <td class="p-2 text-center" rowspan="<%= workout.lifts.map { |lift| lift.groups.count }.sum + 1 %>"><%= link_to workout.date, workout_path(workout.id) %>
            </td>
            <td class="p-2 text-center" rowspan="<%= workout.lifts.map { |lift| lift.groups.count }.sum + 1 %>"><%= workout.workout_name %></td>
            <td class="p-2 text-center" rowspan="<%= workout.lifts.map { |lift| lift.groups.count }.sum + 1 %>"><%= workout.total.round %></td>
        </tr>
        <% workout.lifts.each do |lift| %>
          <% lift.groups.each_with_index do |group, index| %>
            <tr class="<%= row_color %>">
              <% if index == 0 %>
                <td class="p-2 text-center" rowspan="<%= lift.groups.count %>"><%= lift.lift_name %></td>
              <% end %>
              <td class="p-2 text-center"><%= group.reps %></td>
              <td class="p-2 text-center"><%= group.weight %></td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/workouts/new.html.erb
<div class="flex justify-center">
  <div class="m-12 border rounded-lg shadow-md w-4/5 sm:w-4/5 md:w-3/5 lg:w-1/2 xl:w-2/5 p-7">
    <%= form_with model: @workout do |form| %>
      <div class="flex justify-between flex-col sm:flex-row rounded">
        <div class="w-full sm:mr-1">
          <%= form.label :date, class: "text-sm font-medium" %>
          <%= form.date_field :date, required: true, class: "rounded-md w-full" %>
        </div>
        <div class="w-full sm:ml-1">
          <%= form.label :workout_name, 'Workout Name (optional)', class: "text-sm font-medium" %>
          <%= form.text_field :workout_name, class: "rounded-md w-full" %><br>
        </div>
      </div>

      <div data-controller="calculator" data-action="click->calculator#calculateTotalWeight">
        <div data-controller="nested-form">
          <%= form.fields_for :lifts, Lift.new, child_index: 0 do |lift| %>
            <%= render 'lift_fields', form: lift %>
          <% end %>
          <template data-nested-form-target="liftTemplate">
            <%= form.fields_for :lifts, Lift.new, child_index: 'TEMPLATE_LIFT' do |lift| %>
              <%= render 'lift_fields', form: lift %>
            <% end %>
          </template>
          <div data-nested-form-target="addLift">
            <button class="text-green-700" data-action="nested-form#addLift">Add Lift</button>
          </div>
        </div>

        <%= form.label :total, 'Total Weight Moved', class: "text-sm font-medium" %><br>
        <%= form.text_field :total, data: {
            calculator_target: "totalWeight" }, class: "rounded-md w-1/2" %>
      </div>
      <% if user_signed_in? %>
        <%= form.submit "Save Workout", class: "border rounded-md p-1 mt-1 bg-slate-100" %><br>
      <% end %>
    <% end %>
    <% if flash[:error].present? %>
      <div class="alert alert-danger">
        <%= flash[:error] %>
      </div>
    <% end %>
  </div>
</div>

app/views/workouts/show.html.erb
<h1 class="text-center text-2xl p-2"><%= @workout.date %> <%= @workout.workout_name unless @workout.workout_name.empty? %></h1>
<div class="flex justify-center">
  <table class="text-center">
    <thead>
      <tr>
        <th class="p-2 text-center">Total</th>
        <th class="p-2 text-center">Lift Name</th>
        <th class="p-2 text-center">Reps</th>
        <th class="p-2 text-center">Weight</th>
      </tr>
    </thead>
    <tbody>
        <% row_color = cycle('bg-gray-100', 'bg-white') %>
        <tr class="<%= row_color %>">
            <td class="p-2 text-center" rowspan="<%= @workout.lifts.map { |lift| lift.groups.count }.sum + 1 %>"><%= @workout.total.round %></td>
        </tr>
        <% @workout.lifts.each do |lift| %>
          <% lift.groups.each_with_index do |group, index| %>
            <tr class="<%= row_color %>">
              <% if index == 0 %>
                <td class="p-2 text-center" rowspan="<%= lift.groups.count %>"><%= lift.lift_name %></td>
              <% end %>
              <td class="p-2 text-center"><%= group.reps %></td>
              <td class="p-2 text-center"><%= group.weight %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
  </table>
</div>
<div class="flex justify-center">
  <%= link_to 'Delete Workout', workout_path(@workout), method: :delete, data: {turbo_method: :delete,
      turbo_confirm: "Are you sure?" }, class: 'text-red-500 hover:text-red-700' %>
</div>